repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master, --pattern, '\d\.\d\.\d']
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      #- id: terraform_tflint Current version requires provider being upgraded to 4.0 which contains breaking changes
      - id: terraform_tfsec
      - id: terraform_checkov
